version: "3"
services:
  hover:
    build: hover
    environment:
      - HOVER_USERNAME
      - HOVER_PASSWORD
      - HOVER_DNS_ID
      - ARCH
    entrypoint: bash
    command: /app/hover/start.sh




